#' Add a Labelled Bracket to Group Predictors in a Dot-and-Whisker Plot
#'
#' \code{add_bracket} draws a bracket along the y-axis beyond the plotting area of a dot-and-whisker plot generated by \code{dwplot}, useful for labelling a group of predictors
#'
#' @param p A dot-and-whisker plot generated by \code{dwplot}
#' @param label The text to appear on the bracket
#' @param top The name of the topmost variable to be bracketed as a character string, or alternately, the numeric position of this variable, counting from the bottom of the y-axis
#' @param bottom The name of the bottommost variable to be bracketed as a character string, or alternately, the numeric position of this variable, counting from the bottom of the y-axis
#' @param xloc
#' @param face Options for label text: "plain", "bold", "italic", "oblique", and "bold.italic"
#' @param last logical: Is this the last bracket to be added to the plot?
#'
#' @return The function returns a \code{ggplot} (if \code{last = FALSE}) or \code{gtable} (if \code{last = TRUE}) object.
#'
#' @examples
#' data(mtcars)
#' m1 <- lm(mpg ~ wt + cyl + disp, data = mtcars)
#' m1_df <- tidy(m1) # create data.frame of regression results
#'
#' p <- dwplot(m1_df) +
#'     scale_y_discrete(breaks = 4:1, labels=c("Intercept", "Weight", "Cylinders", "Displacement")) +
#'     theme_bw() + xlab("Coefficient") + ylab("") +
#'     geom_vline(xintercept = 0, colour = "grey50", linetype = 2) +
#'     theme(legend.position="none")
#'
#' p %>% add_bracket(label="Engine", top="cyl", bottom=1) %>% add_bracket(label="Not Engine", top=4, bottom=3, xloc=-29, last = TRUE)
#'
#' @import grid gridExtra gtable
#'
#' @export

add_bracket <- function(p, label, top, bottom, face="italic") {
    pd <- p$data
    if (is.character(top)) top <- pd$y_ind[which(unique(pd$term)==top)]
    if (is.character(bottom)) bottom <- pd$y_ind[which(unique(pd$term)==bottom)]

    overhang <- max(pd$y_ind)/40
    p1 <- p + theme(plot.margin = unit(c(rep(1, 3), 1.4), c(rep("lines", 3), "cm")))

    match_background_theme <- function(bg) {
        theme_bw() %+replace% theme(line = )

    n_vars <- length(unique(p$data$term))
    p2 <- ggplot(p$data, aes(x = -1, y = y_ind)) + geom_point() +
        coord_cartesian(ylim = c(.5, n_vars+.5), xlim = c(0, 1)) +
        xlab(p$labels$x) + ylab("") + theme_bw() +
        theme_update(line = element_blank(),
                     rect = element_blank(),
                     strip.text = element_text(colour = p$theme$plot.background$colour),
                     axis.text = element_text(colour = p$theme$plot.background$colour),
                     plot.title = element_text(colour = p$theme$plot.background$colour),
                     axis.title = element_text(colour = p$theme$plot.background$colour)) +
        theme(axis.title.x = element_text(colour = p$theme$plot.background$colour),
              plot.margin = unit(c(1, -.5, 1, 0), "lines")) +
        scale_x_continuous(expand = c(0,0)) +
        annotation_custom(
            grob = textGrob(label = label, gp = gpar(cex = .7, fontface = face), rot = 90),
            ymin = (top+bottom)/2, ymax = (top+bottom)/2,
            xmin = .22, xmax = .22) +
        annotation_custom(grob = linesGrob(), xmin = .6, xmax = .6, ymin = bottom-overhang, ymax = top+overhang) +
        annotation_custom(grob = linesGrob(), xmin = .6, xmax = 1, ymin = top+overhang, ymax = top+overhang) +
        annotation_custom(grob = linesGrob(), xmin = .6, xmax = 1, ymin = bottom-overhang, ymax = bottom-overhang)

    g1 <- ggplotGrob(p1)
    g2 <- gtable_filter(ggplotGrob(p2), pattern = "panel", trim = TRUE, fixed=TRUE)

    g <- gtable_add_grob(g1, g2, 3, 1)

    grid.draw(g)
    g
}

#ggsave <- ggplot2::ggsave; body(ggsave) <- body(ggplot2::ggsave)[-2]
