#' Add a Labelled Bracket to Group Predictors in a Dot-and-Whisker Plot
#'
#' \code{add_bracket} draws a bracket along the y-axis beyond the plotting area of a dot-and-whisker plot generated by \code{dwplot}, useful for labelling a group of predictors
#'
#' @param p A dot-and-whisker plot generated by \code{dwplot}
#' @param label The text to appear on the bracket
#' @param top The name of the topmost variable to be bracketed as a character string, or alternately, the numeric position of this variable, counting from the bottom of the y-axis
#' @param bottom The name of the bottommost variable to be bracketed as a character string, or alternately, the numeric position of this variable, counting from the bottom of the y-axis
#' @param xloc
#' @param face Options for label text: "plain", "bold", "italic", "oblique", and "bold.italic"
#' @param last logical: Is this the last bracket to be added to the plot?
#'
#' @return The function returns a \code{ggplot} (if \code{last = FALSE}) or \code{gtable} (if \code{last = TRUE}) object.
#'
#' @examples
#' data(mtcars)
#' m1 <- lm(mpg ~ wt + cyl + disp, data = mtcars)
#' m1_df <- tidy(m1) # create data.frame of regression results
#'
#' p <- dwplot(m1_df) +
#'     scale_y_discrete(breaks = 4:1, labels=c("Intercept", "Weight", "Cylinders", "Displacement")) +
#'     theme_bw() + xlab("Coefficient") + ylab("") +
#'     geom_vline(xintercept = 0, colour = "grey50", linetype = 2) +
#'     theme(legend.position="none")
#'
#' p %>% add_bracket(label="Engine", top="cyl", bottom=1, xloc=-29) %>% add_bracket(label="Not Engine", top=4, bottom=3, xloc=-29, last = TRUE)
#'
#' @import grid
#'
#' @export

add_bracket <- function(p, label, top, bottom, face="italic", last = FALSE) {
    pd <- p$data
    if (is.character(top)) top <- pd$y_ind[which(unique(pd$term)==top)]
    if (is.character(bottom)) bottom <- pd$y_ind[which(unique(pd$term)==bottom)]

    overhang <- max(pd$y_ind)/40
#    label_width <- p$scales$scales[[1]]$labels
    xloc <-
    p1 <- p + theme(panel.margin = unit(c(1, 1, 1, 1.3), "lines")) +
        annotation_custom(
            grob = textGrob(label = label, gp = gpar(cex = .7, fontface = face), rot = 90),
            ymin = (top+bottom)/2, ymax = (top+bottom)/2,
            xmin = unit(.05, "lines"), xmax = unit(.05, "lines")) +
        annotation_custom(grob = linesGrob(), xmin = unit(.1, "lines"), xmax = unit(.1, "lines"), ymin = bottom-overhang, ymax = top+overhang) +
        annotation_custom(grob = linesGrob(), xmin = unit(.1, "lines"), xmax = unit(.15, "lines"), ymin = top+overhang, ymax = top+overhang) +
        annotation_custom(grob = linesGrob(), xmin = unit(.1, "lines"), xmax = unit(.15, "lines"), ymin = bottom-overhang, ymax = bottom-overhang)
    if (last==TRUE) {
        gt <- ggplot_gtable(ggplot_build(p1)) # Code to override clipping
        gt$layout$clip[gt$layout$name == "panel"] <- "off"
        grid.draw(gt)
    } else p1
}

