#' Transfer a sample from the posterior distribution of a regression generated by function in \code{\link[MCMCregression]{MCMCregression}} to a data frame that dwplot can read
#' 
#' \code{mcmcdata} transfer result from Bayesian models to make plots using \code{\link[dotwhisker]{dwplot}}.
#'  
#' @param dataset a result from MCMregress or other matrix with each row is a interaction and each column is the sample of the posterior distribution of a coefficient
#' @param model the name of this model. This name will later be used by dwplot to identity different models
#' @param ci_method the method used to calculate credible interval. Can be 'ETI' (default), 'HDI' or 'SI'. More detalis: bayestestR::ci
#' @param ci_sig Value or vector of probability of the CI (between 0 and 1) to be estimated. Default to .89 (89%) for Bayesian models. More detalis: bayestestR::ci
#' @param dens sample size of each sample of posterior distribution. Default is 200.
#' 
#' @return a data frame 
#' 
#' @example 
#' library(MCMCpack)
#' m1 <- MCMCregress(Murder ~ Assault + UrbanPop + Rape, burnin=1000, mcmc=10000, b0=0, B0=0.01, basline="1",mcmc.method="IndMH", data=USArrests)
#' data <- mcmcdata(m1,"model1")
#' 
#' @references 
#' NA
#' 
#' @importFrom bayestestR ci
#' 
#' @export


mcmcdata <- function(dataset, model, ci_method="ETI",ci_sig=.89, dens=200){
  coefficients <- data.frame(stringsAsFactors=FALSE)
  for (i in c(1:ncol(dataset))){
    distrib <- density(dataset[,i],n=dens)
    interm <- data.frame(distrib$x,distrib$y/max(distrib$y),stringsAsFactors=FALSE)
    interm$term <- varnames(dataset)[i]
    interm$model <- model
    interm$estimate <- round(mean(dataset[,i]),4)
    a2 <- bayestestR::ci(c(dataset[,i]),method = ci_method,ci=ci_sig)
    interm$conf.low <- round(a2[[2]],4)
    interm$conf.high <- round(a2[[3]],4)
    coefficients <- rbind(coefficients,interm,stringsAsFactors=FALSE)
  }
  colnames(coefficients)<-c("loc","dens", "term","model","estimate","conf.low","conf.high")
  return(coefficients)
}


