#' Relabel the Predictors in a Tidy Data Frame of Regression Results
#'
#' \code{relabel_predictors} is a convenience function for relabeling the predictors in a tidy data frame to be passed to \code{\link[dotwhisker]{dwplot}} or a plot generated by \code{\link[dotwhisker]{dwplot}}
#'
#' @param x Either a tidy data frame to be passed to \code{\link[dotwhisker]{dwplot}} or a plot generated by \code{\link[dotwhisker]{dwplot}}
#' @param ... Named replacements, as in \code{\link[dplyr]{recode}}.  The argument names should be the current values to be replaced, and the argument values should be the new (replacement) values.  For backwards compatibility, a named character vector, with new values as values, and old values as names may also be used
#'
#' @return The function returns an object of the same type as it is passed: a tidy data frame or a plot generated by \code{\link[dotwhisker]{dwplot}}.
#'
#' @note If x is a plot, any \code{dot_args} arguments specified in the call to \code{\link[dotwhisker]{dwplot}} that generated that plot will be disgarded.  To use \code{relabel_predictors} with \code{dot_args}, pass a tidy data frame instead, then pass the resulting object to \code{\link[dotwhisker]{dwplot}}
#'
#' @examples
#' library(broom)
#' library(dplyr)
#'
#' data(mtcars)
#' m1 <- lm(mpg ~ wt + cyl + disp, data = mtcars)
#' m1_df <- broom::tidy(m1) %>%
#'          relabel_predictors("(Intercept)" = "Intercept",
#'                               wt = "Weight",
#'                               cyl = "Cylinder",
#'                               disp = "Displacement")
#' dwplot(m1_df)
#'
#' dwplot(m1, show_intercept = TRUE) %>%
#'     relabel_predictors("(Intercept)" = "Intercept",
#'                               wt = "Weight",
#'                               cyl = "Cylinder",
#'                               disp = "Displacement")
#'
#'
#' @importFrom dplyr select
#' @importFrom dplyr one_of
#' @import rlang
#'
#' @export

relabel_predictors <- function(x, ...) {
    dots <- rlang::exprs(...)
    if (is.language(dots[[1]])) {
        dots <- split(unname(...), names(...))
    }

    if (is.data.frame(x)) {
        x$term <- dplyr::recode(x$term, !!! dots)
        return(x)
    }
    else if (is.ggplot(x)) {
        x$data$term <- dplyr::recode(x$data$term, !!! dots)
        x$data <- dplyr::select(x$data, one_of(c("model", "term", "estimate", "std.error")))
        x <- dwplot(x$data)
        return(x)
    } else stop("x should be either a tidy data frame or a plot generated by dwplot")
}

